
services:
  db:
    image: postgres
    container_name: cadence 
    environment:
      POSTGRES_USER: reallycreativename
      POSTGRES_PASSWORD: stronkpassword
      POSTGRES_DB: cadencedb
    volumes:
      - mydata:/var/lib/postgresql
    ports:
      - "5432:5432"
volumes:
  mydata: