
services:
  go-backend:
    build: ../
    container_name: cadence_backend
    env_file:
      - ../.env
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis

  db:
    image: postgres 
    container_name: cadence_db 
    environment:
      POSTGRES_USER: reallycreativename
      POSTGRES_PASSWORD: stronkpassword
      POSTGRES_DB: cadencedb
    volumes:
      - mydata:/var/lib/postgresql
    ports:

      - "5432:5432"
  
  redis:
    image: redis:latest
    container_name: cadence_redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --requirepass stronkpassword --appendonly yes
    restart: unless-stopped
volumes:
  mydata:
  redis-data: